version: '3.1'

services:

  db:
    container_name: web_chat_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_chat

  adminer:
    container_name: web_chat_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
